### ISSUE TITLE
Deployment pipeline in Heroku

### ISSUE THREAD

**Issue by Yous91** [Yous91/reliev#33]
**Why ?**

A fully automated deployment process will ensure that nobody ever push the wrong branch in deployment and will ensure that what is on Heroku is always up to date. It will also give us a staging env identical to production where we can test our feature one last time before updating the production (the only env clients see).

**Must have:**

- [ ]  Staging
- [ ]  Prod
- [ ]  Auto deploy master on Staging
- [ ]  Deploy should run migrations

Each should have:

- [ ]  Postgres

**Todo**

- [ ]  Create an heroku pipeline
- [ ]  Create the staging app
- [ ]  Create the prod app
- [ ]  Add postgres on both
- [ ]  Configure heroku so it auto deploys master on staging.
- [ ]  Deploy it
- [ ]  Promote to production
- [ ]  Check that everything is right by running a console in Staging and creating a Company with it.

**Reading list**

- https://www.thehackingproject.org/dashboard/courses/1/weeks/5/days/5?locale=fr
- https://devcenter.heroku.com/articles/pipelines
