### ISSUE TITLE
Add policies

### ISSUE THREAD

**Issue by Yous91** [Yous91/reliev#38]
**Why ?**

Because everyone isn't authorized to do everything.

**Must have**

- [ ]  Proper policies in place
- [ ]  The API must nicely answer with 401 when unauthorized

**Todo**

- [ ]  Add pundit gem

**Reading list**

- https://github.com/varvet/pundit
