### ISSUE TITLE
Add set_profile method

### ISSUE THREAD

**Issue by Yous91** [Yous91/reliev#42]
**Why?**

One user with profile is better.

**Todo**

- [ ] add set_profile method to Company model
- [ ] add `after_create :set_profile` to Company model

- [ ] add set_profile method to Masseur model
- [ ] add `after_create :set_profile` to Masseur model

- [ ] add set_profile method to Employee model
- [ ] add `after_create :set_profile` to Employee model

**Must have**

one profile for all users

**Reading list**

- https://www.thehackingproject.org/dashboard/courses/1/weeks/4/days/5?locale=fr
- https://guides.rubyonrails.org/active_record_callbacks.html

**Comment by Billzero** [comment]
Pourquoi gérer le profile via un after create ?

**Comment by Yous91** [comment]
Pour créer automatiquement un profil après la création d'un(e) company/masseur/employee.
