### ISSUE TITLE
Create_event

### ISSUE THREAD

**Issue by Yous91** [Yous91/reliev#85]
**Why ?**

To allow employees to have a massage.

**Todo**

- [ ] `$ rails g model Event title:string description:text masseur:string participating_employees:string moment:string maximum_number_of_participation:interger`

- [ ] add to migration : `t.belongs_to :company, index: true`

- [ ] `$ rails db:migrate`

- [ ] add association : 

- `has_many :events to` model/company.rb
-   `belongs_to :company `to model/event.rb

**Must have**

**Reading list**
